image: "rustlang/rust:nightly"

stages:
  - build
  - test

build:
  stage: build
  script:
    - git submodule update --init --recursive
    - (cd bentofs && make)
    - (cd hello_ll/rust && make)
    - (cd xv6fs/rust && make)

test:
  stage: test
  script:
    - git submodule update --init --recursive
    - (cd bentofs && make)
    - (cd hello_ll/rust && make)
    - sudo insmod bentofs/bentofs.ko
    - sudo insmod hello_ll/rust/hello_ll.ko
    - sudo mkdir /mnt/hello
    - sudo mount -t bentoblk -o fd=10,rootmode=40000,user_id=0,group_id=0,blksize=4096,name=hello_ll -o loop hello_ll/hello /mnt/hello
    - sudo cat /mnt/hello/hello
    - sudo umount /mnt/hello
    - sudo rmmod hello_ll
    - sudo rmmod bentofs
